//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }

        /// <summary>
        /// Id
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Login
        /// </summary>
        [Display(Name = "Login", Description = "4 - 20 characters")]
        [Required(ErrorMessage = "k")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "k")]
        public string Login { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        [Display(Name = "Password")]
        [Required]
        [DataType(DataType.Password)]
        [StringLength(256)]
        public string Password { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Display(Name = "Name", Description = "4 - 20 characters")]
        [Required(ErrorMessage = "k")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "k")]
        public string Name { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [Display(Name = "Email", Description = "Your Email address")]
        [Required(ErrorMessage = "k")]
        [EmailAddress(ErrorMessage = "k")]
        public string Email { get; set; }

        /// <summary>
        /// Role of the user, host or not
        /// </summary>
        public bool IsHost { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
